baseURL: https://icodeit.org
title: I Code It
paginate: 5
theme: PaperModX

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
googleAnalytics: UA-28217566-1

permalinks:
  posts: :slug

minify:
  disableXML: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10
        - name: About
          url: about/
          weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON

disqusShortname: icodeit

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  TocSide: 'left'
  description: "I Code It - code and life - https://icodeit.org"
  author: 邱俊涛 | Juntao Qiu
  keywords: [Blog, Clean Code, Refactoring, Development, Software]
  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  tocopen: true

  comments: true

  homeInfoParams:
    Title: Code and Life
    Content: >
      - 你好，我是邱俊涛。我是一名[程序员](https://github.com/abruzzi)，一个[技术作家](https://leanpub.com/u/juntao)，也是一个[创作者](https://www.youtube.com/@icodeit.juntao)。我享受写代码，尤其享受重构代码 -- 一点点的剔除坏掉的，晦涩的片段，最终变成容易读懂，容易修改的代码。我尤其喜欢将这种化繁为简的技术教给别人的感觉。
      
      - 2018年之后，我的很多技术总结也会以英文发布在[medium](https://juntao-qiu.medium.com/)上，不过我通常也会随后将其翻译成中文并记录在这里。

  socialIcons:
    - name: github
      url: "https://github.com/abruzzi"
    - name: youtube
      url: "https://www.youtube.com/@icodeit.juntao"      
    - name: medium
      url: "https://juntao-qiu.medium.com/"
    - name: twitter
      url: "https://twitter.com/juntaoqiu"
    - name: linkedin
      url: "https://www.linkedin.com/in/juntao-qiu-b865501b/"      

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  highlight:
      noClasses: false
  goldmark:
    renderer:
      unsafe: true
